Revert "Always add InnerXml to ComplexType"
Looking at the git history I see the following three events:
 - I had guarded InnerXml support - available in case we knew for sure
 InnerXml is needed
 - then we went with InnerXml being parsed all the time
 - then we saw some problems and disable InnerXml together

Not trying to be impolite to outside contributors, but boy haven't
the original design been better than the current end state?

This reverts commit ac7b5f08a8ff8beeda439934ba258af7340d1619 and 032abf4c777fa62c7d8b57f21037882f2851c7ec

Addressing:
+ go vet ./...
Error: pkg/scap/models/cpe_language/models.go:84:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:96:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:110:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:126:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:134:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:144:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:158:2: struct field innerXml has xml tag but is not exported
Error: pkg/scap/models/cpe_language/models.go:167:2: struct field innerXml has xml tag but is not exported
... and thousand other