Do export schema that contains only simple types
This is related to recent changes in 8f04406bff44464b7c0f169a6ce4f7f2fe25dbea.

Addressing compile current errors of GoComply/scap like:

GO111MODULE=on go test ./...
?   	github.com/gocomply/scap/pkg/bz2	[no test files]
?   	github.com/gocomply/scap/pkg/scap/constants	[no test files]
 # github.com/gocomply/scap/pkg/scap/models/cpe_dict
pkg/scap/models/cpe_dict/models.go:23:7: undefined: cpe.Cpe22Type
pkg/scap/models/cpe_dict/models.go:27:15: undefined: cpe.Cpe22Type
pkg/scap/models/cpe_dict/models.go:64:7: undefined: cpe.Cpe22Type
pkg/scap/models/cpe_dict/models.go:68:15: undefined: cpe.Cpe22Type